
(function(){
const lower='abcdefghijklmnopqrstuvwxyz',upper=lower.toUpperCase(),digits='0123456789';
const mapRange=(startLower,startUpper,startDigits)=>{const m={};[...lower].forEach((c,i)=>m[c]=String.fromCodePoint(startLower+i));[...upper].forEach((c,i)=>m[c]=String.fromCodePoint(startUpper+i));if(startDigits)[...digits].forEach((c,i)=>m[c]=String.fromCodePoint(startDigits+i));return m};
const bold=mapRange(0x1d41a,0x1d400,0x1d7ce),italic=mapRange(0x1d44e,0x1d434),boldItalic=mapRange(0x1d482,0x1d468),sans=mapRange(0x1d5a0,0x1d5ba,0x1d7e2),sansBold=mapRange(0x1d5d4,0x1d5be,0x1d7ec),sansItalic=mapRange(0x1d608,0x1d622),sansBoldItalic=mapRange(0x1d63c,0x1d656),mono=mapRange(0x1d68a,0x1d670,0x1d7f6),double=mapRange(0x1d552,0x1d538),fraktur=mapRange(0x1d526,0x1d504),boldScript=mapRange(0x1d4ea,0x1d4d0);
const circled={};[...lower,...upper,...digits].forEach(c=>{const n=c.charCodeAt(0);circled[c]=n>=97&&n<=122?String.fromCodePoint(0x24d0+n-97):n>=65&&n<=90?String.fromCodePoint(0x24b6+n-65):String.fromCodePoint(0x24ea+n-48)});
const fullwidth={};[...lower,...upper,...digits].forEach(c=>fullwidth[c]=String.fromCodePoint(c.charCodeAt(0)+0xfee0));
const smallCaps=Object.fromEntries([...lower].map(c=>[c,({'a':'ᴀ','b':'ʙ','c':'ᴄ','d':'ᴅ','e':'ᴇ','f':'ꜰ','g':'ɢ','h':'ʜ','i':'ɪ','j':'ᴊ','k':'ᴋ','l':'ʟ','m':'ᴍ','n':'ɴ','o':'ᴏ','p':'ᴘ','q':'ǫ','r':'ʀ','s':'s','t':'ᴛ','u':'ᴜ','v':'ᴠ','w':'ᴡ','x':'x','y':'ʏ','z':'ᴢ'})[c]||c]));
const supers=Object.fromEntries([...lower,...digits].map(c=>[c,({'a':'ᵃ','b':'ᵇ','c':'ᶜ','d':'ᵈ','e':'ᵉ','f':'ᶠ','g':'ᵍ','h':'ʰ','i':'ⁱ','j':'ʲ','k':'ᵏ','l':'ˡ','m':'ᵐ','n':'ⁿ','o':'ᵒ','p':'ᵖ','r':'ʳ','s':'ˢ','t':'ᵗ','u':'ᵘ','v':'ᵛ','w':'ʷ','x':'ˣ','y':'ʸ','z':'ᶻ','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'})[c]||c]));
const subs=Object.fromEntries([...lower,...digits].map(c=>[c,({'a':'ₐ','e':'ₑ','h':'ₕ','i':'ᵢ','j':'ⱼ','k':'ₖ','l':'ₗ','m':'ₘ','n':'ₙ','o':'ₒ','p':'ₚ','r':'ᵣ','s':'ₛ','t':'ₜ','u':'ᵤ','v':'ᵥ','x':'ₓ','0':'₀','1':'₁','2':'₂','3':'₃','4':'₄','5':'₅','6':'₆','7':'₇','8':'₈','9':'₉'})[c]||c]));
const regional=Object.fromEntries([...lower].map(c=>[c,String.fromCodePoint(0x1f1e6+c.charCodeAt(0)-97)]));
const transforms=[['Mathematical Bold',bold],['Mathematical Italic',italic],['Mathematical Bold Italic',boldItalic],['Sans-Serif',sans],['Sans-Serif Bold',sansBold],['Sans-Serif Italic',sansItalic],['Sans-Serif Bold Italic',sansBoldItalic],['Monospace',mono],['Double Struck',double],['Gothic / Fraktur',fraktur],['Bold Script',boldScript],['Bubble',circled],['Fullwidth',fullwidth],['Small Caps',smallCaps],['Superscript',supers],['Subscript',subs],['Regional Flags',regional],['Bold Bubble',Object.assign({},circled,bold)],['Italic Bubble',Object.assign({},circled,italic)],['Bold Fullwidth',Object.assign({},fullwidth,bold)],['Cursive Small Caps',Object.assign({},smallCaps,boldScript)],['Monospace Fullwidth',Object.assign({},fullwidth,mono)],['Fraktur Bubble',Object.assign({},circled,fraktur)],['Script Bubble',Object.assign({},circled,boldScript)],['Sans Bubble',Object.assign({},circled,sans)]];
const decorations=[['','',''],['✦ ',' ✦',''],['♡ ',' ♡',''],['୨୧ ',' ୨୧',''],['【 ',' 】',''],['⋆｡°✩ ',' ✩°｡⋆','']];
const toStyle=(text,m)=>[...text].map(c=>m[c]||m[c.toLowerCase()]||c).join('');
const styles=[];transforms.forEach(([name,m])=>decorations.forEach(([pre,suf])=>styles.push({name:pre?name+' · Decorated':name,key:name.toLowerCase(),render:t=>pre+toStyle(t,m)+suf})));
function renderFontStyles(){const box=$('#fontResults');if(!box)return;const text=$('#fontTextInput')?.value||'';const q=text.trim().toLowerCase();const filtered=styles.filter(s=>!q||s.key.includes(q)||s.name.toLowerCase().includes(q));$('#fontCount').textContent=`${filtered.length} of ${styles.length} styles available`;box.innerHTML='';filtered.forEach(s=>{const card=document.createElement('div');card.className='font-style-card';const meta=document.createElement('div');meta.className='font-style-name';meta.textContent=s.name;const row=document.createElement('div');row.className='font-style-row';const sample=document.createElement('div');sample.className='font-style-sample';sample.textContent=text?s.render(text):'available today';const btn=document.createElement('button');btn.className='font-copy-btn';btn.type='button';btn.textContent='▣ Copy';btn.addEventListener('click',()=>copyText(sample.textContent,btn));row.append(sample,btn);card.append(meta,row);box.append(card)})}
$('#fontTextInput')?.addEventListener('input',renderFontStyles);$('#clearFontText')?.addEventListener('click',()=>{$('#fontTextInput').value='';renderFontStyles();$('#fontTextInput').focus()});if($('#fontResults'))renderFontStyles();
})();
